# Rust formatting configuration
edition = "2021"
max_width = 100
use_small_heuristics = "Max"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true