apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nimbus-data
  namespace: nimbus
  labels:
    app: nimbus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard